### ISSUE TITLE
High resource usage over time (memory leak?)

### ISSUE THREAD

**Issue by TruncatedDinoSour** [element-hq/dendrite#3446]
### Background information

- **Dendrite version or git SHA**: 0.13.8+79b87c7
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: go version go1.23.0 linux/amd64
- **Client used (if applicable)**: Schildichat, Element, Hydrogen, or CinnyChat is what most people use I believe on the HS

### Description

- **What** is the problem: Dendrite, when running over time, begins hogging ram over time. This results in not only a big RAM hog, but also a CPU hog, since I run zRAM (maybe also related to dendrite using the CPU? Idk.) Regardless, every week or so I have to restart Dendrite because it keeps eating more and more RAM, making the overall server performance worse.
- **Who** is affected: The server.
- **How** is this bug manifesting: It appears as Dendrite runs in long-term, slowly eating more and more RAM and/or swap.
- **When** did this first appear: I can't recall. I don't remember needing to restart dendrite before 1.18 I think.

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org, @s7evink:matrix.org or @devonh:one.ems.host
with a link to the respective Github issue, thanks!
-->

- Run dendrite
- Use it for a week or so
- Watch the resource, mainly RAM, usage grow over time

This is its resource usage only 2 days later after its most recent restart. And it only creeps over time until I restart it:

![image](https://github.com/user-attachments/assets/fe720451-3cfb-4b4f-9227-9f84da47f4dc)

It's weird.

**Comment by TruncatedDinoSour** [comment]
Had to restart it again. Could only last 3 days.

**Comment by TruncatedDinoSour** [comment]
s7evink/fetch-auth-events fixed it

**Comment by TruncatedDinoSour** [comment]
nvm lmao

**Comment by neilalexander** [comment]
No idea if zRAM is a setup that should be supported but without a memory profile it will be difficult to tell what’s going on. 

https://element-hq.github.io/dendrite/development/profiling

**Comment by TruncatedDinoSour** [comment]
> a setup that should be supported but without a memory profile it will be difficult

it is zram, yeah
but, is profiling a good choice over like a week ? the report would be huge, no ?
and even so, wouldnt it severely impact the performance for the week ? is there a way to check this with minimal disruption ?

**Comment by neilalexander** [comment]
You just need a single memory profile captured when the memory usage is high. That should contain enough info and the files are small.

**Comment by TruncatedDinoSour** [comment]
> You just need a single memory profile captured when the memory usage is high. That should contain enough info and the files are small.
> 
> Having profiling enabled has next to no runtime cost so it’s fine to have it switched on for a long time.

oh nice, okay then, ill enable the profiler tomorrow since for today i consider myself done and want the rest of the day offish xD

ill send out a memory profile capture in 1-3 days in this thread :)

**Comment by TruncatedDinoSour** [comment]
ok since it was just 1 environment variable i enabled it now, thought maybe its more complicated but nope

**Comment by TruncatedDinoSour** [comment]
@neilalexander okay i got the heap report, idk how safe it is to send out heap reports, ive heard that its generally acceptable but for now ill stick to web ui screenshots

it is at 2.5 gigs of ram usage atm according to systemd, or was at the time when i took the report, it dropped to 2.2 now

```
● dendrite.service - dendrite
     Loaded: loaded (/etc/systemd/system/dendrite.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-12-12 21:13:13 UTC; 1 day 16h ago
   Main PID: 271785 (dendrite)
      Tasks: 20 (limit: 19144)
     Memory: 2.2G
        CPU: 2h 17min 46.905s
     CGroup: /system.slice/dendrite.service
             └─271785 /home/matrix/go/bin/dendrite --config dendrite.yaml
```

had to restart dendrite 2 days ago since it was refusing to write to postgresql database and both sending and receiving messages was slow :)

if you need the actual report in full lmk

![image](https://github.com/user-attachments/assets/17f3230a-0c9a-49aa-963a-92d220be6071)

phony.run is 64% somehow

![image](https://github.com/user-attachments/assets/23a6d2ae-763b-405d-b60f-669ed35bb266)

![image](https://github.com/user-attachments/assets/f281bfe1-bad3-49fd-9dfa-a05d97342ecf)

something about sql dbs, im using postgres if it matters

![image](https://github.com/user-attachments/assets/80346ee0-49a3-486a-a8dd-711ea7922693)

graph : 

![image](https://github.com/user-attachments/assets/45a0ed79-4c89-4951-b594-5a70cda942bc)

![image](https://github.com/user-attachments/assets/de5e6fd2-bfe4-4dfb-b66e-9b60665ee582)

![image](https://github.com/user-attachments/assets/3654ba66-9ce6-486d-b9f1-b26b89252ae0)

**Comment by TruncatedDinoSour** [comment]
iirc @jjj333-p has experienced a similar issue with dendrite, may have extra input ?

**Comment by neilalexander** [comment]
Looks like it's struggling to process events. Can you try switching your instance to #3447 and see if it improves after a couple hours?

**Comment by TruncatedDinoSour** [comment]
> Looks like it's struggling to process events. Can you try switching your instance to #3447 and see if it improves after a couple hours?

the pr or the s7evink/fetch-auth-events branch ? im already on the branch if thats what youre asking, i can try the pr i guess

**Comment by jjj333-p** [comment]
i face this same issue, i can say that the fetch-auth-events pr did help a lot but its still not fixed. i also notice that after about a week of uptime it will be near oom on my system (full 4gb of ram + zram), and then i reboot and both the cpu and ram usage are way down (10-15% avg cpu, only 1-2gb of ram used). i also have all the caching i can disabled in the config. idk how helpful to this i can be though sorry

**Comment by jjj333-p** [comment]
![image](https://github.com/user-attachments/assets/231aff98-ed17-4d37-ab54-3c7c1e2d6f38)
dendrite itself (after 2 days up) is using 1.8gb of ram, and the postgres dedicated to just it and the sliding sync proxy is using another half a gig or more depending on how busy it is

heres it after restarting the dendrite service
![image](https://github.com/user-attachments/assets/b2f62157-1a25-48b6-83fe-b960c61d1cd9)

**Comment by jjj333-p** [comment]
ill also note that when rooms like the abandoned genshin impact room start backfilling in (thanks t2bot for not working correclty ever) it does max out the cpu and raise ram some, but not to that level. its a gradual over time thing.

![image](https://github.com/user-attachments/assets/48f70044-de82-42bf-90ef-04c9602fbc5e)

**Comment by neilalexander** [comment]
@TruncatedDinoSour Can you attach the full profile?

**Comment by TruncatedDinoSour** [comment]
> @TruncatedDinoSour Can you attach the full profile?

sure

[heap.gz](https://github.com/user-attachments/files/18136325/heap.gz)

**Comment by TruncatedDinoSour** [comment]
> > @TruncatedDinoSour Can you attach the full profile?
> 
> sure
> 
> [heap.gz](https://github.com/user-attachments/files/18136325/heap.gz)

ftr if it wasnt clear this is gzipped xD as in

`gzip -d heap.gz` for the actual profile

i had to gzip it cuz github cried about the raw one

**Comment by TruncatedDinoSour** [comment]
istg i cant even run it for 3 days without it crying in agony ugh

**Comment by neilalexander** [comment]
I saw it was gzipped yeah, it looks a lot like the profile is just showing the server is crunching some extremely complex room state. Are you a member of any very large or complex rooms?

**Comment by TruncatedDinoSour** [comment]
> I saw it was gzipped yeah, it looks a lot like the profile is just showing the server is crunching some extremely complex room state. Are you a member of any very large or complex rooms?

no and i dont think anyone on the hs really is

**Comment by neilalexander** [comment]
Any interesting log entries happening at the time? Particularly `level=error`?

**Comment by TruncatedDinoSour** [comment]
> Any interesting log entries happening at the time? Particularly `level=error`?

not that i see from recent logs, some media stuff but other than that nothing worth of concern i believe

**Comment by TruncatedDinoSour** [comment]
> > Any interesting log entries happening at the time? Particularly `level=error`?
> 
> not that i see from recent logs, some media stuff but other than that nothing worth of concern i believe

turns out 1 user was a part of the matrix.org HQ maybe thats why

**Comment by neilalexander** [comment]
Try using the admin API `evacuateRoom` to force everyone out of that room and see if things calm down. (Afterwards you could try purging it too, just in case the room state is corrupt from former auth errors.)

**Comment by TruncatedDinoSour** [comment]
> Try using the admin API `evacuateRoom` to force everyone out of that room and see if things calm down. (Afterwards you could try purging it too, just in case the room state is corrupt from former auth errors.)

dont worry i am using both evac and remove right now

its taking some time but its working

regardless, the resource usage only has been a problem recently when that account has been there since the start of the homeserver so idk

maybe itll help ? idk, well see i guess :D

**Comment by bones-was-here** [comment]
If you "need" to host huge rooms on a system without much RAM you might benefit from disabling the in-memory cache:
```
global:
  cache:
    max_age: 0s
```
The cost is somewhat more work for postgres.

**Comment by TruncatedDinoSour** [comment]
> If you "need" to host huge rooms on a system without much RAM you might benefit from disabling the in-memory cache:
> 
> ```
> global:
>   cache:
>     max_age: 0s
> ```
> 
> The cost is somewhat more work for postgres.

i did a while ago alrd
